### ISSUE TITLE
100% packet loss with turnutils_uclient

### ISSUE THREAD

**Issue by lapseofreason** [instrumentisto/coturn-docker-image#11]
I am trying to set up a TURN server, but when I try to connect to it with

`turnutils_uclient -v -m 1 -W XXXXXXXXXXXXXXXX www.example.com`

I get 100% lost packets, even though connecting to the server seems to work fine.

Here is the complete log: [turnutils_uclient.log](https://github.com/instrumentisto/coturn-docker-image/files/3552645/turnutils_uclient.log)

When I use wireshark to look at the traffic on the bridge interface of the docker container, it seems that while all kinds of control packets go back and forth, the actual data packages at the end go from the client to the server, but there is no response.

My configuration and docker-compose file is as follows:
[turnserver.conf.txt](https://github.com/instrumentisto/coturn-docker-image/files/3552648/turnserver.conf.txt)
[docker-compose.yml.txt](https://github.com/instrumentisto/coturn-docker-image/files/3552650/docker-compose.yml.txt)

Any idea what could be wrong here? Are the response packets dropped by docker or is the server not responding?

**Comment by tyranron** [comment]
@lapseofreason hard to tell at first glance.
1. Did you try to use `network: host` configuration for container to see if issue reproduces there?
2. What Coturn logs did say?

**Comment by lapseofreason** [comment]
@tyranron Thanks for your reply! The result is exactly the same with the following command:

`docker run --rm --network=host --name coturn-test -v /srv/conf/coturn/turnserver.conf:/etc/coturn/turnserver.conf:Z -v /srv/log/coturn/:/var/log/:Z instrumentisto/coturn:4.5  -c /etc/coturn/turnserver.conf --log-file=/var/log/coturn.log --external-ip='$(detect-external-ip)' -V`

Here is the log: [coturn_2019-08-29.log](https://github.com/instrumentisto/coturn-docker-image/files/3555343/coturn_2019-08-29.log)

It looks like after line 709 the server is sending data responses:
```
34: udp_server_input_handler:628:start
34: read_client_connection:4443:start
34: read_client_connection: data.buffer=0x5569d1fde24c, data.len=104
34: read_client_connection: wrote to peer 100 bytes
34: read_client_connection:4513:end
34: udp_server_input_handler:666:end
```
In wireshark I can see those packets with 100 bytes going from the client to the server, but no response. I don't know why they are not sent back, do you have any idea?

**Comment by lapseofreason** [comment]
I was also able to reproduce this on my local computer as follows:

```
docker run -d --rm --name coturn-test --network=host instrumentisto/coturn -n --log-file=stdout --external-ip='$(detect-external-ip)' -v

turnutils_uclient -v localhost
```

I even tried to turn off selinux and stop firewalld, but it did not help.

**Comment by tyranron** [comment]
@lapseofreason hmm... did you try this test with some public available TURN/STUN server?

**Comment by lapseofreason** [comment]
@tyranron I could not find a public one that was reachable, any suggestions on which one I could try?

**Comment by tyranron** [comment]
@lapseofreason consider https://numb.viagenie.ca/

**Comment by lapseofreason** [comment]
@tyranron Hmm, it didn't work either. I then tried to register my docker instance with my Nextcloud server and it seemed to work. I have no idea how I could verify though that the traffic is actually going through coturn and not peer-to-peer.

Any idea how I could test this? Or how do you check if your coturn server is working?

**Comment by tyranron** [comment]
@lapseofreason so, I suppose something wrong with the test itself.

We're usually testing this by hand via reproducing NAT situation and see if only `relay` ICE candidates are present and WebRTC video/audio actually works. Sometimes it requires custom code modifications which filter only `relay` ICE candidates among other.

Also [Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) is quite helpful.

**Comment by lapseofreason** [comment]
I have found no good way to test this without code modifications, but I have tried to make calls in multiple scenarios and all of them worked. So I'm not sure whether the traffic was really relayed, but for lack of a better way to test this I'll close this.

Thanks a lot @tyranron for your help!
