### ISSUE TITLE
Unable to deploy docker image

### ISSUE THREAD

**Issue by Sudheerkumar** [instrumentisto/coturn-docker-image#14]
We are getting this issue when we are deploying it to a cluster 
standard_init_linux.go:211: exec user process caused “no such file or directory”

All the files are in the standard unix format. Help Appreciated.

**Comment by tyranron** [comment]
@Sudheerkumar unfortunately I don't understand what to advice you with due to the lack of information.

How exactly it was deployed (docker run command, docker-compose/Kubernetes specs, mounts)?  
How exactly Coturn is configured?  
Is there any more verbose output? Did you try `--verbose` flag?

**Comment by Sudheerkumar** [comment]
using yaml files.
built the docker images and deploying to cluster using the yaml files.

Haven't tried `--verbose`, just tried to deploy the image as is from the github

**Comment by tyranron** [comment]
@Sudheerkumar well, it would be better if you provide the YAML specs and describe the case you're using the image for.

Making Coturn work for you case may be tricky, and usually this involves `--network=host` to be used as Docker is no quite OK with port ranges.

You can read more about possible issues and context we're using this image in #13. Maybe some advices form there will help you.
