### ISSUE TITLE
Preferrable transport

### ISSUE THREAD

**Issue by Sudheerkumar** [instrumentisto/coturn-docker-image#17]
Hi what is the preferrable transport mode for webrtc? tcp or udp?

and what is the preferred mode of url while calling from webapp.

is it one of the following or all of them work?

turn:<IP>:3478?transport=udp
turn:<IP>:3478?transport=tcp
stun:<IP>:3478?transport=tcp
stun:<IP>:3478?transport=udp

we are trying to evaluate coturn for our internal projects. Please help us on this

**Comment by tyranron** [comment]
@Sudheerkumar I guess it would be better to ask in the repos/forums relative to your WebRTC solution used, as requirements may differ depending on concrete implementation.

Regarding our case, we're using Coturn with Kurento. Here is the docs explaining preferred settings for Coturn:
https://doc-kurento.readthedocs.io/en/6.13.0/user/installation.html#stun-and-turn-servers
https://doc-kurento.readthedocs.io/en/6.13.0/user/faq.html#how-to-install-coturn

We use the following ICE servers on clients:
```json
{
   "ice_servers":[
      {
         "urls":[
            "stun:my.domain:3478"
         ]
      },
      {
         "urls":[
            "turn:my.domain:3478",
            "turn:my.domain:3478?transport=tcp"
         ],
         "username":"<static-user>",
         "credential":"<static-path>"
      }
   ]
}
```

Also, see more tips in #13
