### ISSUE TITLE
Does this image support exclusive turn/turns over 80/443 ?

### ISSUE THREAD

**Issue by Sudheerkumar** [instrumentisto/coturn-docker-image#22]
Does this image support exclusive turn/turns over 80/443 ?

Because if we put` no-stun` flag enabled it still doesnt goes through TURN(observed in the WIRESHARK) 

We are struggling to get past through our corporate network, any pointers please?

We are unable to see `relay` candidates when we go to a corporate network or a corporate VPN.

**Comment by Sudheerkumar** [comment]
Hi, any support for us please?

**Comment by tyranron** [comment]
@Sudheerkumar this image supports everything that [supports Coturn itself](https://github.com/coturn/coturn/blob/upstream/4.5.1.1/examples/etc/turnserver.conf). [Here](https://github.com/instrumentisto/coturn-docker-image/blob/22919bc49de712f056f0688db3b83dd289a711c0/Dockerfile#L43-L51) you can see how exactly Coturn is compiled for this Docker image. There is nothing else except that.

Your question is about Coturn usage, not the image itself. Maybe it's better to ask it [in upstream](https://github.com/coturn/coturn/issues)?

> Does this image support exclusive turn/turns over 80/443 ?

[`listening-port`](https://github.com/coturn/coturn/blob/upstream/4.5.1.1/examples/etc/turnserver.conf#L14-L18) and [`tls-listening-port`](https://github.com/coturn/coturn/blob/upstream/4.5.1.1/examples/etc/turnserver.conf#L20-L30) are supported by Coturn. You may try to use them for that.

> We are struggling to get past through our corporate network, any pointers please?

> Hi, any support for us please?

We're not Coturn/TURN/STUN experts, nor network engineers, nor upstream maintainers. We can't and won't offer any support of that kind, see [the license](https://github.com/instrumentisto/coturn-docker-image/blob/22919bc49de712f056f0688db3b83dd289a711c0/LICENSE.md).

Everything we provide is just a _simple_ Docker image with built Coturn inside.

**Comment by Sudheerkumar** [comment]
Sure, Thanks.
