### ISSUE TITLE
Feature - Support others architectures

### ISSUE THREAD

**Issue by killua99** [instrumentisto/coturn-docker-image#24]
This is an example repository how to implement support for others architectures.

https://github.com/killua99/coturn-docker-image

I hope we could open a PR if you want to support such of thing.

**Comment by tyranron** [comment]
@killua99 we don't mind to support other architectures. However, we kinda dislike the idea to build images in Travis CI and then push to Docker Hub. It would be wonderful to continue to rely on Docker Hub automated builds. It should be possible [with some `hooks/` magic](https://github.com/docker/hub-feedback/issues/1261).

**Comment by SuperSandro2000** [comment]
Docker HUB is first of all extremely slow and IIRC does not support multi arch builds without a modified base image where you are cross compiling in.

I find it unacceptable to wait 6 or sometimes even 12 hours for a docker image to show up on Docker HUB when I can build it locally in 5 minutes or less. Also adding quite a few MBs for qemu is also not ideal and cross building especially arm64 on amd64 is extremely slow and would be a better fit for travis's arm64 native.

**Comment by tyranron** [comment]
@SuperSandro2000 given Coturn releases appear not so often, it's quite acceptable for the images to appear within 48 hours after new release is out. Regarding the fact that I don't react immediately anyway. So, why bother about +/- few hours?

Docker Hub automated builds, despite their slowness and bugs, simplify image maintaince a lot by auto-updating readme, auto-linking GitHub repo, and etc.

**Comment by tyranron** [comment]
Hmm.. here is a good example: https://github.com/jmb12686/go-loadtest-api

Need to quite a think about `hooks/` reorganization, as some ideas have appeared to play with.

**Comment by SuperSandro2000** [comment]
I bother about a few days if there is an important security update especially when TURN server spike in popularity like now.

There is a [GitHub Action which can update the readme](https://github.com/factoriotools/factorio-docker/blob/master/.travis.yml#L34) and if your are basically writing all commands into hooks I see no difference when you just do the full build yourself.

Also doing buildx together with manifests is just needlessly complicated as buildx combines all manifests with tagging, building cross arch and pushing into one command.

**Comment by killua99** [comment]
@tyranron the idea was to show the whole process how to build with multi-platform the travis build works but is more like a showcase how to achieve that.

I believe you build on Docker Hub. Doing local builds are quite fast if you are not running on a laptop and some laptop with many cores and fast hard drive (the SSD drive) could make it even faster.

You could see the times that it takes to build it on travis and adding the previous setup of the environment.

The issue with the way of go-loadtest-api of doing build is not convenient or antiquated. 

Compare how tags looks on:
- https://hub.docker.com/r/jmb12686/go-loadtest-api/tags
- https://hub.docker.com/r/killua99/coturn/tags
- https://hub.docker.com/_/redis/tags

Is more convenient use `instrumentisto/coturn:latest` and the architecture fix it by itself.

I see instrumentisto has many docker images to maintain I see the point to try to make it someway automatic. What about using an internal pipeline to build images? could that fix the issue of building images?

**Comment by tyranron** [comment]
Official `coturn/coturn` Docker image now supports it.

It wiil be released with a stable tag in a while.
