### ISSUE TITLE
Merging of Docker image into official repo?

### ISSUE THREAD

**Issue by OmegaVVeapon** [instrumentisto/coturn-docker-image#25]
Hi,

I was wondering if there was an official Docker image for Coturn and stumbled upon [this](https://github.com/coturn/coturn/issues/273) in the issue tracker.

From the comments, this repo was recommended and after going through the code here, I find it to be the most elegant implementation of this Docker image available.

My question is, is there a reason these changes have not been merged back to the official repo?

**Comment by tyranron** [comment]
@OmegaVVeapon thank you for taking care about this question.

Actually, I had just created it once for my company/team needs and then was supporting it on daily routine basis. I haven't proposed it as official image yet, 'cause haven't seen much sense in it (the image is quite simple, after all). But if community wants something like that, I'm totally OK to move my work into official repo and support it there.

I've [asked about it there](https://github.com/coturn/coturn/issues/273#issuecomment-623639653), and if maintainers don't mind, I'll do the job.

**Comment by OmegaVVeapon** [comment]
Thank you so much!

I saw your comment and I hope they approve it. :+1: 

I think alot of people would benefit from that.

**Comment by misi** [comment]
@tyranron  I am as coturn repository maintainer would like invite you to maintain in coturn the docker image part. So please contact me and I would be very happy if we could merge our efforts!
