### ISSUE TITLE
Deploy to kubernets

### ISSUE THREAD

**Issue by maxwill9457** [instrumentisto/coturn-docker-image#26]
Hi, I'm seeking a way to run a TURN server on Kubernetes cluster.
Is this docker image suitable running on Kubernetes?
I have made yaml file below and  been able to create coturn service.
However, I couldn't reach my coturn service from Trickle ICE.
How can I solve this problem? Thank you

turnserver-pod.yaml
[turnserver-pod.txt](https://github.com/instrumentisto/coturn-docker-image/files/4621985/turnserver-pod.txt)

Executed command
$ kubectl apply -f turnserver-pod.yaml
$ kubectl expose deployment turnserver-pod --type=LoadBalancer --name=turnserver-pod-service --external-ip=184.172.234.20

$ kubectl get services
NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)          AGE
kubernetes               ClusterIP      172.21.0.1       <none>           443/TCP          4d23h
turnserver-pod-service   LoadBalancer   172.21.110.165   184.172.234.20   3478:32037/TCP   8m8s

**Comment by tyranron** [comment]
@maxwill9457 we're using this image exactly in Kubernetes. However, Docker (which is default Kubernetes CRI) is quite bad with mapping big port ranges. That's why we're using `hostNetwork: true` for all out Cuturn deployments.

**Comment by maxwill9457** [comment]
@tyranron thanks for the quick reply! I have saw your reply in the other issue, and I will try the iptable setting for kubernetes on IBM cloud.
https://github.com/instrumentisto/coturn-docker-image/issues/16
