### ISSUE TITLE
SQLite connection closed

### ISSUE THREAD

**Issue by markmadlangbayan** [instrumentisto/coturn-docker-image#28]
Hello,  I'm getting an error above when I tried to use turnadmin.

I just need to add an admin user.

```bash
/ # turnadmin -L --db /var/lib/coturn/turndb
0: log file opened: /var/log/turn_30_2020-08-04.log
0: SQLite connection was closed.

**Comment by zhaoxingyun** [comment]
me too. need help~

**Comment by tyranron** [comment]
@zhaoxingyun @markmadlangbayan please, refer to [`turnadmin` man page](https://www.mankier.com/1/turnadmin) for that. Or [ask the question in the Coturn repository](https://github.com/coturn/coturn/issues).

This has nothing with the Docker image itself.
