### ISSUE TITLE
What is the username and password for accessing the turn server

### ISSUE THREAD

**Issue by akh64bit** [instrumentisto/coturn-docker-image#29]
I understand that we can start the server using the command 'docker run -d --network=host instrumentisto/coturn'
What is the username and password that is needed for accessing the server?
My application needs to access the turn server by specifying something like below.

**var pc_config = {"iceServers": [{"url":"turn:my_username@<turn_server_ip_address>", "credential":"my_password"}]};
pc_new = new webkitRTCPeerConnection(pc_config);**

I am not sure what is `credential` and `my_password` above when using this docker image.

Any help would be appreciated.

Thanks.

**Comment by tyranron** [comment]
@akh64bit you should consider [Coturn's `turnserver` configuration](https://github.com/coturn/coturn/wiki/turnserver). This Docker image doesn't do anything except using that one.

Coturn has multiple authentication mechanisms.

**Comment by akh64bit** [comment]
Thank you so much @tyranron for the pointer. I was able to resolve the issue :)
