### ISSUE TITLE
Where can I set the username and password for the Turn service?

### ISSUE THREAD

**Issue by CrazyDeveloper007** [instrumentisto/coturn-docker-image#31]
First,thank the author for providing such a convenient Docker Image.
My question is shown in the title.
PS:I'm Chinese developer.My English is so poor.

**Comment by tyranron** [comment]
@guojinming007 as [was stated in #29](https://github.com/instrumentisto/coturn-docker-image/issues/29#issuecomment-679148777), Coturn has multiple authentication mechanisms.

You should look in [official docs of Coturn's `turnserver` configuration](https://github.com/coturn/coturn/wiki/turnserver) and choose the desired one.

For now I'm closing this as this is not the Docker image issue.

**Comment by CrazyDeveloper007** [comment]
> @guojinming007 as [was stated in #29](https://github.com/instrumentisto/coturn-docker-image/issues/29#issuecomment-679148777), Coturn has multiple authentication mechanisms.
> 
> You should look in [official docs of Coturn's `turnserver` configuration](https://github.com/coturn/coturn/wiki/turnserver) and choose the desired one.
> 
> For now I'm closing this as this is not the Docker image issue.

Again, thank you very much.
