### ISSUE TITLE
turn server username password 

### ISSUE THREAD

**Issue by bendney** [instrumentisto/coturn-docker-image#32]
What is the turn username password ?

**Comment by tyranron** [comment]
@bendney are you kidding me? The second in a row today... 😕

Please, use [search in issues](https://github.com/instrumentisto/coturn-docker-image/issues?q=is%3Aissue+is%3Aclosed+password) before creating a new one.

And see the answers: https://github.com/instrumentisto/coturn-docker-image/issues/29#issuecomment-679148777, https://github.com/instrumentisto/coturn-docker-image/issues/31#issuecomment-707630135
