### ISSUE TITLE
TURN server issue

### ISSUE THREAD

**Issue by bendney** [instrumentisto/coturn-docker-image#33]
what is the turn username and password ?

**Comment by tyranron** [comment]
@bendney have you read [the answer on your previous issue](https://github.com/instrumentisto/coturn-docker-image/issues/32#issuecomment-707824481)?

Please, don't act like that and don't spam issues. Next time I'll be made to ban you from this repo.

**Comment by bendney** [comment]
Sorry, i didn't see the issue I wrote before, and I think that I haven't created successfully, so I ceated another one. I'll close it
