### ISSUE TITLE
Service 'coturn' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder360299840/rootfs: no such file or directory

### ISSUE THREAD

**Issue by hmz4dev** [instrumentisto/coturn-docker-image#36]
I get this error when run Dockerfile

**Comment by tyranron** [comment]
@hmz4dev I guess you're using `build` directive for `coturn` service in `docker-compose.yml`. Just don't do that. Use built images from Docker Hub.

**Comment by hmz4dev** [comment]
@tyranron  it's the same

**Comment by hmz4dev** [comment]
@tyranron  its work now  thank's
