### ISSUE TITLE
Prometheus?

### ISSUE THREAD

**Issue by chriswiggins** [instrumentisto/coturn-docker-image#37]
Would there be any resistance into me opening a PR to add prometheus support into this image? Would be helpful for us but I'd rather not manage our own fork of this repo 👍

**Comment by tyranron** [comment]
@chriswiggins go ahead 👍

But consider that this image eventually will be deprecated (in fact moved to official Coturn repo).

**Comment by chriswiggins** [comment]
Yep thats cool - hoping that any changes I make here will move across?

**Comment by tyranron** [comment]
@chriswiggins sure!

**Comment by tyranron** [comment]
Fixed in https://github.com/coturn/coturn/pull/754
