### ISSUE TITLE
detect-external-ip doesn't work

### ISSUE THREAD

**Issue by voipdev** [instrumentisto/coturn-docker-image#8]
docker run -d --network=host instrumentisto/coturn \
           -n --log-file=stdout \
           --external-ip=$(detect-external-ip) \
           --relay-ip=$(detect-external-ip)

bash: detect-external-ip: command not found

**Comment by targs08** [comment]
@voipdev, we had some mistake in our documentation. You should use the next command: 

```
docker run -d --network=host instrumentisto/coturn  \
-n --log-file=stdout \
--external-ip='$(detect-external-ip)' \
--relay-ip='$(detect-external-ip)'
```
